DROP TABLE RPS.GameSummary;
CREATE TABLE RPS.GameSummary (id BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), clientGesture VARCHAR(255), date TIMESTAMP, result VARCHAR(255), serverGesture VARCHAR(255), PRIMARY KEY (id));





